# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jan DC
tagline:             'Musings of a CS Student'
description:         'A personal blog involving rants varying from code development to random observations on the internet. This site was built with <a href="http://jekyllrb.com" target="_blank">Jekyll</a>.'
url:                 http://jankdc.com
baseurl:             /
paginate:            10

# About/contact
author:
  name:              Jan Karlo Dela Cruz
  url:               http://jankdc.com
  email:             jankarlo.delacruz@gmail.com

github:
  repo:              https://github.com/jankdc/jankdc.com

# Custom vars
version:             1.0.0
